//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Client.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ClientTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_LOGIN                310
#define IDR_USERFRE_TOOLBAR             311
#define IDD_DIALOG_USERINPUT            314
#define IDD_DIALOG_USERSEARCH           315
#define IDD_DIALOG_USERADDFRIENDREPLY   317
#define IDD_DIALOG_USERADDFRIENDREPLY_REMOTE 318
#define IDR_MENU_USERLIST_POPMENU       318
#define IDD_DIALOG_GROUPSEARCH          319
#define IDR_MENU_GROUPLIST_POP          319
#define IDD_DIALOG_USERADD              320
#define IDD_DIALOG_REGIST               321
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_BUTTON_DLG_INPUT_SEND       1003
#define IDC_EDIT_DLG_INPUT              1008
#define IDC_EDIT_USERSEARCH_INPUT       1010
#define IDC_LIST_USERSEARCH_RESULT      1011
#define IDC_BUTTON_USERSEARCH_SEARCH    1012
#define IDC_EDIT_DIALOG_USERADDFRIENDREPLY_MSG 1014
#define IDC_STATIC_DIALOG_USERADDFRIENDREPLY 1015
#define IDC_STATIC_DIALOG_USERADDFRIENDREPLY_REMOTE 1016
#define IDC_EDIT_GROUPSEARCH_INPUT      1017
#define IDC_LIST_GROUPSEARCH_RESULT     1018
#define IDC_BUTTON_GROUPSEARCH_SEARCH   1019
#define IDC_EDIT_DIALOG_USERADDFRIENDREPLY_REPLY_MSG 1020
#define IDC_STATIC_TIP                  1021
#define IDC_EDIT_USERADD_MSG            1022
#define IDC_EDIT_REGIST_NAME            1023
#define IDC_EDIT_REGIST_PASSWORD        1024
#define IDC_EDIT_REGIST_PASS_RE         1025
#define ID_BTN_REGIST                   1027
#define ID_BUTTON32771                  32771
#define ID_BUTTON_TOOL_USERSEARCH       32771
#define ID_POP_32773                    32773
#define ID_POP_USERLIST_POPMENU_DELETEUSER 32774
#define ID_BUTTON_TOOL_GROUPSEARCH      32775
#define ID_IDR_32776                    32776
#define ID_IDR_GROUP_QUIT               32777
#define IDS_STRING_MYFRIEND             0xEF13

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
